name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Ruby 3.1j
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.7
    - name: Set up packages
      run: |
        sudo apt install libncurses5-dev -y
    - name: Build
      run: |
        gem install bundler
        gem install rubocop
        bundle install --jobs 4 --retry 3
    - name: and test with minitest
      run: rake test
    - name: Rubocop
      run: rubocop
